apiVersion: v1
kind: Secret
metadata:
  name: coconut-secrets
  namespace: default
type: Opaque
stringData:
  db-root-password: "coconut123"
  db-name: "coconut_store"
  jwt-secret: "coconutsecret2024_superSecure!"
  rzp-key-id: "rzp_test_CHANGE_ME"
  rzp-key-secret: "CHANGE_ME"
  rzp-webhook-secret: "CHANGE_ME"
  upi-id: "natucoconut@upi"
  upi-name: "NatuCoconut"
