apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  db-root-password: {{ .Values.secret.dbRootPassword | quote }}
  db-name: {{ .Values.secret.dbName | quote }}
  jwt-secret: {{ .Values.secret.jwtSecret | quote }}
  rzp-key-id: {{ .Values.secret.rzpKeyId | quote }}
  rzp-key-secret: {{ .Values.secret.rzpKeySecret | quote }}
  rzp-webhook-secret: {{ .Values.secret.rzpWebhookSecret | quote }}
  upi-id: {{ .Values.secret.upiId | quote }}
  upi-name: {{ .Values.secret.upiName | quote }}
